-- MySQL Script generated by MySQL Workbench
-- vie 07 oct 2016 13:05:43 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tarea
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tarea
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tarea` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `tarea` ;

-- -----------------------------------------------------
-- Table `tarea`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tarea`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `tarea`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `usuario` VARCHAR(100) NULL COMMENT '',
  `pass` VARCHAR(100) NULL COMMENT '',
  `rol` TINYINT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `tarea`.`noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tarea`.`noticias` ;

CREATE TABLE IF NOT EXISTS `tarea`.`noticias` (
  `id_noticia` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `titulo` VARCHAR(255) NULL COMMENT '',
  `texto` TEXT NULL COMMENT '',
  PRIMARY KEY (`id_noticia`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tarea`.`usuarios`
-- -----------------------------------------------------
START TRANSACTION;
USE `tarea`;
INSERT INTO `tarea`.`usuarios` (`id`, `usuario`, `pass`, `rol`) VALUES (1, 'admin', 'admin', 1);
INSERT INTO `tarea`.`usuarios` (`id`, `usuario`, `pass`, `rol`) VALUES (2, 'user', 'user', 2);

COMMIT;

